export const dataRows = {
    status: "ok",
    data: [
        {
            SheetName: "Phrases",
            Uid: "DCYH22OL",
            En: "day off",
            Ru: "выходной",
            Lcnt: 23,
            Asf: 21,
            Asr: 3,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861887552
        },
        {
            SheetName: "Phrases",
            Uid: "DD9EU4B5",
            En: "in bulk",
            Ru: "оптом",
            Lcnt: 23,
            Asf: 21,
            Asr: 3,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767522521943
        },
        {
            SheetName: "Phrases",
            Uid: "DDCRZ58L",
            En: "long run",
            Ru: "долгосрочная перспектива",
            Lcnt: 22,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861899341
        },
        {
            SheetName: "Phrases",
            Uid: "DDEMIMGS",
            En: "get to the bottom",
            Ru: "добраться до сути",
            Lcnt: 29,
            Asf: 21,
            Asr: 6,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861913731
        },
        {
            SheetName: "Phrases",
            Uid: "DDE1JAPI",
            En: "plane took off thirty minutes late",
            Ru: "самолет взлетел на тридцать минут позже",
            Lcnt: 30,
            Asf: 21,
            Asr: 7,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861935132
        },
        {
            SheetName: "Phrases",
            Uid: "4DH7W7EJ",
            En: "could you do me a favor",
            Ru: "не могли бы вы оказать мне услугу",
            Lcnt: 29,
            Asf: 21,
            Asr: 6,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861949790
        },
        {
            SheetName: "Phrases",
            Uid: "4DJEEANM",
            En: "officer pulls over the man in the pickup",
            Ru: "офицер останавливает мужчину в пикапе",
            Lcnt: 30,
            Asf: 21,
            Asr: 6,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861966191
        },
        {
            SheetName: "Phrases",
            Uid: "4DHC786N",
            En: "without hesitation",
            Ru: "без колебаний",
            Lcnt: 23,
            Asf: 21,
            Asr: 3,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861976022
        },
        {
            SheetName: "Phrases",
            Uid: "NSK699YY",
            En: "to minimize the damage to the project",
            Ru: "чтобы минимизировать ущерб проекту",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862108005
        },
        {
            SheetName: "Phrases",
            Uid: "NS3HZYZJ",
            En: "estimate how the changes could affect current work",
            Ru: "оценивать влияние изменений на текущую работу",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862127215
        },
        {
            SheetName: "Phrases",
            Uid: "VGB4PXYP",
            En: "stable service operation",
            Ru: "стабильная работа сервиса",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862141366
        },
        {
            SheetName: "Phrases",
            Uid: "VFSJM49E",
            En: "balanced decision",
            Ru: "взвешенное решение",
            Lcnt: 22,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862153025
        },
        {
            SheetName: "Phrases",
            Uid: "EH5EG2TI",
            En: "under tight deadlines",
            Ru: "в условиях сжатых сроков",
            Lcnt: 21,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767522716385
        },
        {
            SheetName: "Phrases",
            Uid: "EHE9JBL5",
            En: "hasty conclusions",
            Ru: "поспешные выводы",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862174715
        },
        {
            SheetName: "Phrases",
            Uid: "EH6DH1KD",
            En: "solution, aimed at ensuring high fault tolerance of the system",
            Ru: "решение направленное на обеспечение высокой отказоустойчивости системы",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862214335
        },
        {
            SheetName: "Phrases",
            Uid: "EH4PGB6M",
            En: "rather than complaining, why not try to find a solution",
            Ru: "вместо того, чтобы жаловаться, почему бы не попытаться найти решение",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862244573
        },
        {
            SheetName: "Phrases",
            Uid: "EHCUSBAT",
            En: "the project aims to encourage cooperation rather than competition",
            Ru: "цель проекта поощрять сотрудничество, а не конкуренцию",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862402121
        },
        {
            SheetName: "Phrases",
            Uid: "EH4D5RNL",
            En: "to take steps toward optimization",
            Ru: "предпринять шаги направленные на оптимизацию",
            Lcnt: 24,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862426851
        },
        {
            SheetName: "Phrases",
            Uid: "EH4TGAUW",
            En: "helps professional growth",
            Ru: "помогает профессиональному росту",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862440212
        },
        {
            SheetName: "Phrases",
            Uid: "EH58QTU1",
            En: "without sacrificing quality",
            Ru: "не жертвуя качеством",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862452561
        },
        {
            SheetName: "Phrases",
            Uid: "0Z673PD3",
            En: "meet the deadline",
            Ru: "уложиться в срок",
            Lcnt: 22,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862461822
        },
        {
            SheetName: "Phrases",
            Uid: "0Z843OMP",
            En: "It is worth refraining from hasty conclusions",
            Ru: "cтоит воздержаться от поспешных выводов",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862484872
        },
        {
            SheetName: "Phrases",
            Uid: "0ZE9G4RZ",
            En: "ensure system stability",
            Ru: "обеспечивать стабильность системы",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862498102
        },
        {
            SheetName: "Phrases",
            Uid: "0Z8TOWSJ",
            En: "improve system reliability",
            Ru: "повышать надёжность системы",
            Lcnt: 22,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862514772
        },
        {
            SheetName: "Phrases",
            Uid: "0ZET2KPE",
            En: "ensure high availability",
            Ru: "обеспечивать высокую доступность",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862531072
        },
        {
            SheetName: "Phrases",
            Uid: "0Z7OKOV5",
            En: "maintain stable service operation",
            Ru: "поддерживать стабильную работу сервиса",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862547532
        },
        {
            SheetName: "Phrases",
            Uid: "0Z5NW102",
            En: "improve overall performance",
            Ru: "улучшать общую производительность",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862559102
        },
        {
            SheetName: "Phrases",
            Uid: "0Z9U2TVI",
            En: "reduce latency",
            Ru: "снижать задержки",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862567752
        },
        {
            SheetName: "Phrases",
            Uid: "0Z6J0ZHH",
            En: "increase throughput",
            Ru: "увеличивать пропускную способность",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862587032
        },
        {
            SheetName: "Phrases",
            Uid: "0Z9MMDRS",
            En: "optimize resource usage",
            Ru: "оптимизировать использование ресурсов",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862599402
        },
        {
            SheetName: "Phrases",
            Uid: "ZEPP8JWP",
            En: "built for fault tolerance",
            Ru: "построено с учётом отказоустойчивости",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862611912
        },
        {
            SheetName: "Phrases",
            Uid: "ZEHSVSMI",
            En: "result in service downtime",
            Ru: "приводить к простою сервиса",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862631052
        },
        {
            SheetName: "Phrases",
            Uid: "ZFHFRIS9",
            En: "prepared for peak traffic",
            Ru: "подготовлено к пиковому трафику",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862643352
        },
        {
            SheetName: "Phrases",
            Uid: "ZG1JCKYR",
            En: "contribute to system stability",
            Ru: "способствовать стабильности системы",
            Lcnt: 22,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862657402
        },
        {
            SheetName: "Phrases",
            Uid: "0Z5H1O25",
            En: "avoid performance degradation",
            Ru: "избегать деградации производительности",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862672882
        },
        {
            SheetName: "Phrases",
            Uid: "ZEIKM583",
            En: "designed for scalability",
            Ru: "спроектировано с учётом масштабируемости",
            Lcnt: 22,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862685222
        },
        {
            SheetName: "Phrases",
            Uid: "ZEG7PALJ",
            En: "lead to operational issues",
            Ru: "приводить к операционным проблемам",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862926646
        },
        {
            SheetName: "Phrases",
            Uid: "0Z606PT0",
            En: "increase fault tolerance",
            Ru: "повышать отказоустойчивость",
            Lcnt: 23,
            Asf: 21,
            Asr: 1,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862942979
        },
        {
            SheetName: "Phrases",
            Uid: "37Q5BNYV",
            En: "result in performance degradation",
            Ru: "приводить к деградации производительности",
            Lcnt: 22,
            Asf: 21,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767862969458
        },
        {
            SheetName: "Phrases",
            Uid: "37PAL5Z2",
            En: "respond to failures",
            Ru: "реагировать на сбои",
            Lcnt: 22,
            Asf: 21,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767863068203
        },
        {
            SheetName: "Phrases",
            Uid: "37PGGEX0",
            En: "support professional growth",
            Ru: "поддерживать профессиональный рост",
            Lcnt: 22,
            Asf: 21,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767863080242
        },
        {
            SheetName: "Phrases",
            Uid: "37YNFPSJ",
            En: "contribute to the team's professional growth",
            Ru: "способствовать профессиональному росту команды",
            Lcnt: 22,
            Asf: 21,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767863104832
        },
        {
            SheetName: "Phrases",
            Uid: "38W3UG5M",
            En: "establish best practices",
            Ru: "внедрять лучшие практики",
            Lcnt: 22,
            Asf: 20,
            Asr: 0,
            Aef: 1,
            Aer: 0,
            Aw: "",
            Ts: 1767893693170
        },
        {
            SheetName: "Phrases",
            Uid: "37PC7VGE",
            En: "add to system complexity",
            Ru: "увеличивать сложность системы",
            Lcnt: 22,
            Asf: 21,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767893810709
        },
        {
            SheetName: "Phrases",
            Uid: "ZEI09TIC",
            En: "result in data loss",
            Ru: "приводить к потере данных",
            Lcnt: 21,
            Asf: 20,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861824350
        },
        {
            SheetName: "Phrases",
            Uid: "ZEH3Q7N1",
            En: "contribute to long-term maintainability",
            Ru: "способствовать долгосрочной сопровождаемости",
            Lcnt: 21,
            Asf: 20,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861844592
        },
        {
            SheetName: "Phrases",
            Uid: "ZFG2BT1S",
            En: "optimized for high load",
            Ru: "оптимизировано под высокую нагрузку",
            Lcnt: 21,
            Asf: 20,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861856721
        },
        {
            SheetName: "Phrases",
            Uid: "0ZENUR0L",
            En: "reduce operational risks",
            Ru: "снижать операционные риски",
            Lcnt: 21,
            Asf: 20,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767861867002
        },
        {
            SheetName: "Phrases",
            Uid: "ZEJOERR6",
            En: "lead to predictable behavior",
            Ru: "приводить к предсказуемому поведению",
            Lcnt: 20,
            Asf: 20,
            Asr: 0,
            Aef: 0,
            Aer: 0,
            Aw: "",
            Ts: 1767522502724
        },
        {
            SheetName: "Phrases",
            Uid: "IEI7HUB7",
            En: "stakeholders engagement",
            Ru: "взаимодействие с заинтересованными сторонами",
            Lcnt: "",
            Asf: "",
            Asr: "",
            Aef: "",
            Aer: "",
            Aw: "",
            Ts: ""
        },
        {
            SheetName: "Phrases",
            Uid: "IDLJP61Q",
            En: "i'm getting a little bit ahead of myself",
            Ru: "я немного забегаю вперед",
            Lcnt: "",
            Asf: "",
            Asr: "",
            Aef: "",
            Aer: "",
            Aw: "",
            Ts: ""
        }
    ]
};