export const dataRows = {
    status: "ok",
    data: [
{ SheetName: "Demo", Uid: "W001", En: "I", Ru: "я" },
  { SheetName: "Demo", Uid: "W002", En: "you", Ru: "вы" },
  { SheetName: "Demo", Uid: "W003", En: "he", Ru: "он" },
  { SheetName: "Demo", Uid: "W004", En: "she", Ru: "она" },
  { SheetName: "Demo", Uid: "W005", En: "we", Ru: "мы" },
  { SheetName: "Demo", Uid: "W006", En: "they", Ru: "они" },
  { SheetName: "Demo", Uid: "W007", En: "be", Ru: "быть" },
  { SheetName: "Demo", Uid: "W008", En: "have", Ru: "иметь" },
  { SheetName: "Demo", Uid: "W009", En: "do", Ru: "делать" },
  { SheetName: "Demo", Uid: "W010", En: "go", Ru: "идти" },
  { SheetName: "Demo", Uid: "W011", En: "man", Ru: "мужчина" },
  { SheetName: "Demo", Uid: "W012", En: "woman", Ru: "женщина" },
  { SheetName: "Demo", Uid: "W013", En: "people", Ru: "люди" },
  { SheetName: "Demo", Uid: "W014", En: "time", Ru: "время" },
  { SheetName: "Demo", Uid: "W015", En: "day", Ru: "день" },
  { SheetName: "Demo", Uid: "W018", En: "work", Ru: "работа" },
  { SheetName: "Demo", Uid: "W020", En: "bad", Ru: "плохой" },
  { SheetName: "Demo", Uid: "W021", En: "new", Ru: "новый" },
  { SheetName: "Demo", Uid: "W022", En: "old", Ru: "старый" },
  { SheetName: "Demo", Uid: "W023", En: "big", Ru: "большой" },
  { SheetName: "Demo", Uid: "W024", En: "small", Ru: "маленький" },
  { SheetName: "Demo", Uid: "W025", En: "different", Ru: "разный" },
  { SheetName: "Demo", Uid: "W026", En: "this", Ru: "этот" },
  { SheetName: "Demo", Uid: "W027", En: "that", Ru: "тот" },
  { SheetName: "Demo", Uid: "W037", En: "and", Ru: "и" },
  { SheetName: "Demo", Uid: "W038", En: "but", Ru: "но" },
  { SheetName: "Demo", Uid: "W039", En: "because", Ru: "потому что" },
  { SheetName: "Demo", Uid: "W040", En: "very", Ru: "очень" },
  { SheetName: "Demo", Uid: "W041", En: "really", Ru: "действительно" },
  { SheetName: "Demo", Uid: "W043", En: "often", Ru: "часто" },
  { SheetName: "Demo", Uid: "W044", En: "sometimes", Ru: "иногда" },
  { SheetName: "Demo", Uid: "W045", En: "here", Ru: "здесь" },
  { SheetName: "Demo", Uid: "W046", En: "there", Ru: "там" },
  { SheetName: "Demo", Uid: "W047", En: "now", Ru: "сейчас" },
  { SheetName: "Demo", Uid: "W048", En: "today", Ru: "сегодня" },
  { SheetName: "Demo", Uid: "W049", En: "yes", Ru: "да" },
  { SheetName: "Demo", Uid: "W050", En: "no", Ru: "нет" }
]
};